version: '3.1'

services:
  # https://hub.docker.com/_/mariadb
  db:
    image: mariadb:10.3
    restart: always
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - medshakeehr

  medshakeehr:
    image: medshakeehrdocker:dev
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      SELF_SIGNED_HOST: ${VIRTUAL_HOST}
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_LIMIT: 512M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - proxy
      - medshakeehr

  # https://hub.docker.com/r/jwilder/nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
      
  # https://hub.docker.com/r/sebastienheyd/self-signed-proxy-companion
  proxy-companion:
    restart: always
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs

# # https://hub.docker.com/r/jodogne/orthanc    
#   orthanc:
#     image: jodogne/orthanc-plugins:1.9.7
#     command: /run/secrets/  # Path to the configuration files (stored as secrets)
#     ports:
#       - 4242:4242
#       - 8042:8042
#     secrets:
#       - orthanc.json
#     environment:
#       - ORTHANC_NAME=HelloWorld
      
# secrets:
#   orthanc.json:
#     file: orthanc.json

volumes:
  db-data:
  certs:

networks:
  proxy:
  medshakeehr:
