version: "3"
services:
  web:
    build: 
      context: ./build/${WEBVERSION}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
    container_name: '${COMPOSE_PROJECT_NAME}-${WEBVERSION}'
    restart: 'always'
    depends_on: 
      - database
    networks:
      - msehrlan
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - database
      - orthanc
    volumes: 
      - ${DOCUMENT_ROOT-./ehr}:/app/ehr
      - ${CERT_ROOT-./config/cert}:/app/cert
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

  composer:
    restart: 'no'
    image: composer:2.0
    command: bash -c "composer install && cd public_html && composer install"
    working_dir: /app/ehr 
    depends_on: 
      - web
    volumes:
      - ${DOCUMENT_ROOT-./ehr}:/app/ehr
      
  database:
    image: mariadb:10.5
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - msehrlan

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on: 
      - database
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    networks:
      - msehrlan
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  orthanc:
    image: jodogne/orthanc-plugins:1.8.2
    # command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    networks:
      - msehrlan
    volumes:
      - ${ORTHANC_DATA_DIR-./data/orthanc}:/var/lib/orthanc/db/
    # secrets:
    #   - /config/orthanc/orthanc.json:orthanc.json

# secrets:
#   orthanc.json:
#     file: ./config/orthanc.json

networks:
  msehrlan:
