version: '3.1'

services:
  # https://hub.docker.com/_/mariadb
  db:
    container_name: msehrdb
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
    volumes: 
      - db-data:/var/lib/mysql
      # If you would import old database
      # - ./db-data:/docker-entrypoint-initdb.d
    networks:
      - medshakeehr

  # https://hub.docker.com/_/phpmyadmin  
  # phpmyadmin:
  #     container_name: phpmyadmin
  #     image: phpmyadmin
  #     restart: unless-stopped
  #     environment:
  #       VIRTUAL_HOST: "pma.${VIRTUAL_HOST}"
  #       SELF_SIGNED_HOST: "pma.${VIRTUAL_HOST}"
  #       PMA_HOST: db
  #     networks:
  #       - proxy
  #       - medshakeehr

  medshakeehr:
    container_name: msehr
    image: marsante/msehrtest:7.3.1
    # user: 1000:1000
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      SELF_SIGNED_HOST: ${VIRTUAL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PROTO: ${PROTO}
      COOKIED: ${COOKIED}
      FINGERPRINT: ${FINGERPRINT}
      SQLVARPSWD: ${SQLVARPSWD}
    depends_on:
      - db
      - proxy-companion
    volumes: 
      - medshakeehr:/var/www/html
      # if you use bind volume with arbitrary user create first the folder with the good permissions
      # - ./medshakeehr:/var/www/html
    networks:
      - proxy
      - medshakeehr

  # https://hub.docker.com/r/jwilder/nginx-proxy
  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # rootless socket for user 1000
      # - /run/user/1000/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
      
  # https://hub.docker.com/r/sebastienheyd/self-signed-proxy-companion
  proxy-companion:
    container_name: proxy-companion
    image: sebastienheyd/self-signed-proxy-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # rootless socket for user 1000
      # - /run/user/1000/docker.sock:/var/run/docker.sock:ro

# # https://hub.docker.com/r/jodogne/orthanc    
#   orthanc:
#     container_name: msehrdicom
#     image: jodogne/orthanc-plugins:1.9.7
#     command: /run/secrets/  # Path to the configuration files (stored as secrets)
#     ports:
#       - 4242:4242
#       - 8042:8042
#     secrets:
#       - orthanc.json
#     environment:
#       - ORTHANC_NAME=HelloWorld
      
# secrets:
#   orthanc.json:
#     file: orthanc.json

volumes:
  db-data:
  certs:
  medshakeehr:

networks:
  proxy:
    external: true
  medshakeehr:
